server:
  port: 8080

spring:
  application:
    name: riskscore_mvp

  datasource:
    url: jdbc:${DATABASE_URL}
    username: ${PROD_DB_USERNAME}
    password: ${PROD_DB_PASSWORD}
    driver-class-name: org.postgresql.Driver


  jpa:
    hibernate:
      ddl-auto: update
   




